
CREATE TABLE IF NOT EXISTS Grocer
(
  name VARCHAR PRIMARY KEY,
  items ARRAY  NOT NULL,
  location VARCHAR NOT NULL

);

CREATE TABLE IF NOT EXISTS Consumer
(
  name VARCHAR NOT NULL PRIMARY KEY,
  location VARCHAR NOT NULL

);